# turtle table column and format
---
_id: uuid
monk_type: text
table_name: text
name:  text
creator: text
created_time: text
last_modified: text
description:  text
m: integer
rho: double precision
weights: json
weights_dimension: integer